config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'
  root 'static_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstRailsAppp</title>
      <!-- bootstrap link -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!-- custom css file link -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <!-- javascript links go here -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
     <!-- fonts go here -->
    <link href="https://fonts.googleapis.com/css?family=Cutive|Roboto|Clicker+Script" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data target=".navbar-collapse">
            <span class="sr-only">toggle nav</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="projectName navbar-brand">
            <a href="#">Andora.B</a>
          </div> <!-- /projectName -->
        </div> <!-- /navbar header -->
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", static_pages_about_path %></li>
            <li><%= link_to "Contact", static_pages_contact_path %></li>
          </ul>
        </div> <!-- /navbar collapse -->
      </div> <!-- /container-fluid -->
    </nav> <!-- /navbar -->

    <%= yield %>

    <footer class="site_footer">
      <div class="container-fluid bar">
        <div class="footer-element">&copy; Bike Zürich 2017</div>
      </div>
    </footer>


  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About our company</h1>
<p>We sell bikes since 10 years.You should have the best bike in Switzerland. If you don't want to make a wrong choice,buy by US.</p>

app/views/static_pages/contact.html.erb
<h1>Contact us</h1>
<h2><span class="glyphicon glyphicon-earphone"></span>Tel: 787.237.3888</h2>
<h2><span class="glyphicon glyphicon-envelope"></span> Email: me@me.com</h2>

app/views/static_pages/index.html.erb
<h1>Welcome to Bike Zürich</h1>
<h2>Your source for used bikes in Zürich</h2>
<h2>The best or nothing.<h2>
<%= image_tag("mountainBike.jpg",  class: "img-responsive my-image") %>